/* HOST SHIM: the LINE_* identities from boards/dingopdm_v7/board.h.
   Values are arbitrary but distinct; only identity matters on the host. */
#pragma once

#define GPIOA 0
#define GPIOB 1
#define GPIOC 2
#define GPIOD 3
#define GPIOH 7
#define PAL_LINE(port, pad) ((ioline_t)(((port) << 8) | (pad)))
#define PAL_PAD(line)  ((line) & 0xFFu)
#define PAL_PORT(line) ((line) >> 8)

#define LINE_PF1_IS                 PAL_LINE(GPIOA, 0U)
#define LINE_PF1_IN                 PAL_LINE(GPIOB, 10U)
#define LINE_PF1_DEN                PAL_LINE(GPIOB, 2U)
#define LINE_PF2_IS                 PAL_LINE(GPIOC, 2U)
#define LINE_PF2_IN                 PAL_LINE(GPIOC, 8U)
#define LINE_PF2_DEN                PAL_LINE(GPIOC, 7U)
#define LINE_PF3_4_IS               PAL_LINE(GPIOC, 3U)
#define LINE_PF3_IN                 PAL_LINE(GPIOC, 6U)
#define LINE_PF4_IN                 PAL_LINE(GPIOB, 12U)
#define LINE_PF3_4_DSEL             PAL_LINE(GPIOB, 14U)
#define LINE_PF3_4_DEN              PAL_LINE(GPIOB, 15U)
#define LINE_PF5_6_IS               PAL_LINE(GPIOA, 1U)
#define LINE_PF5_IN                 PAL_LINE(GPIOB, 1U)
#define LINE_PF6_IN                 PAL_LINE(GPIOC, 4U)
#define LINE_PF5_6_DSEL             PAL_LINE(GPIOC, 5U)
#define LINE_PF5_6_DEN              PAL_LINE(GPIOB, 0U)
#define LINE_PF7_8_IS               PAL_LINE(GPIOA, 2U)
#define LINE_PF7_IN                 PAL_LINE(GPIOA, 7U)
#define LINE_PF8_IN                 PAL_LINE(GPIOA, 4U)
#define LINE_PF7_8_DSEL             PAL_LINE(GPIOA, 5U)
#define LINE_PF7_8_DEN              PAL_LINE(GPIOA, 6U)
#define LINE_DI1                    PAL_LINE(GPIOA, 10U)
#define LINE_DI2                    PAL_LINE(GPIOC, 9U)
#define LINE_LED_ERROR              PAL_LINE(GPIOC, 0U)
#define LINE_LED_STATUS             PAL_LINE(GPIOC, 1U)
#define LINE_BATT_SENSE             PAL_LINE(GPIOA, 3U)
#define LINE_USB_VBUS               PAL_LINE(GPIOA, 9U)
#define LINE_CAN_STANDBY            PAL_LINE(GPIOC, 12U)
#define LINE_I2C1_SCL               PAL_LINE(GPIOB, 6U)
#define LINE_I2C1_SDA               PAL_LINE(GPIOB, 7U)
#define LINE_CAN_RX                 PAL_LINE(GPIOB, 8U)
#define LINE_CAN_TX                 PAL_LINE(GPIOB, 9U)
#define LINE_USB_DM                 PAL_LINE(GPIOA, 11U)
#define LINE_USB_DP                 PAL_LINE(GPIOA, 12U)
#define LINE_SWDIO                  PAL_LINE(GPIOA, 13U)
#define LINE_SWCLK                  PAL_LINE(GPIOA, 14U)
#define LINE_SWO                    PAL_LINE(GPIOB, 3U)
#define LINE_E1                     PAL_LINE(GPIOC, 10U)
#define LINE_E2                     PAL_LINE(GPIOC, 11U)
#define LINE_E3                     PAL_LINE(GPIOC, 13U)
#define LINE_UNUSED                 PAL_LINE(GPIOA, 15U)

/* Additional LINE_* names used by the other board variants (dingopdmmax_v1,
   pt-dpdm4_1, canboard_v2).  Values are arbitrary but distinct. */
#define LINE_PF3_IS                 PAL_LINE(GPIOD, 0U)
#define LINE_PF3_DEN                PAL_LINE(GPIOD, 1U)
#define LINE_PF4_IS                 PAL_LINE(GPIOD, 2U)
#define LINE_PF4_DEN                PAL_LINE(GPIOD, 3U)
#define LINE_DI3                    PAL_LINE(GPIOD, 4U)
#define LINE_DI4                    PAL_LINE(GPIOD, 5U)
#define LINE_DI5                    PAL_LINE(GPIOD, 6U)
#define LINE_DI6                    PAL_LINE(GPIOD, 7U)
#define LINE_DI7                    PAL_LINE(GPIOD, 8U)
#define LINE_DI8                    PAL_LINE(GPIOD, 9U)
#define LINE_DO1                    PAL_LINE(GPIOD, 10U)
#define LINE_DO2                    PAL_LINE(GPIOD, 11U)
#define LINE_DO3                    PAL_LINE(GPIOD, 12U)
#define LINE_DO4                    PAL_LINE(GPIOD, 13U)
#define LINE_AI1                    PAL_LINE(GPIOH, 0U)
#define LINE_AI2                    PAL_LINE(GPIOH, 1U)
#define LINE_AI3                    PAL_LINE(GPIOH, 2U)
#define LINE_AI4                    PAL_LINE(GPIOH, 3U)
#define LINE_AI5                    PAL_LINE(GPIOH, 4U)
#define LINE_CAN_ID_1               PAL_LINE(GPIOH, 5U)
#define LINE_CAN_ID_2               PAL_LINE(GPIOH, 6U)
#define LINE_NEOPIXEL_INT           PAL_LINE(GPIOH, 7U)
#define LINE_NEOPIXEL_EXT           PAL_LINE(GPIOH, 8U)
